### PR TITLE
Install dependencies before installing Keylime

### PR DESCRIPTION
**Pull request by mbestavros**
Signed-off-by: Mark Bestavros <mbestavr@redhat.com>

### CODE REVIEW

**Comment by THS-on** [comment]
We install the python packages from the Fedora repo not PyPI: https://github.com/keylime/keylime-vagrant-ansible-tpm-emulator/blob/7a2595a1d2e8b513ef9cced1b5f28595502396fc/roles/ansible-keylime-tpm20/tasks/packages.yml#L22

If there are some missing please add them there.

**Comment by mpeters** [comment]
> We install the python packages from the Fedora repo not PyPI:

I wonder if this is the best approach. It means you have to update that list in-step with the main code repo and creates duplication. And in cases like this, things start breaking for people depending on which version of the code is checked out, etc. So I think a better approach is to just use the same `requirements.txt` file via pip. We have other ways of testing things in Fedora in CI now.

**Comment by mbestavros** [comment]
@THS-on any additional thoughts on @mpeters' comment above?

**Comment by THS-on** [comment]
Because this is only for testing I'm fine with installing the requirements using pip. For a production deployment the packages should be installed using the distro package manager.

**Pull request merged**
